!pip install numpy

In [10]:
import numpy as np

In [11]:
marks = [10, 20, 30]

In [12]:
marks*2

[10, 20, 30, 10, 20, 30]

In [13]:
marks+[2]

[10, 20, 30, 2]

In [14]:
type(marks)

list

In [15]:
arr = np.array(marks)
arr

array([10, 20, 30])

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr*2

array([20, 40, 60])

In [18]:
arr+2

array([12, 22, 32])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(10, 20, 2, dtype='float')

array([10., 12., 14., 16., 18.])

In [21]:
np.arange(10, 20, 1.5)

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

In [22]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
type(arr)

numpy.ndarray

In [24]:
lst = list(range(0, 10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
%timeit [i**2 for i in lst]

559 ns ± 7.75 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
arr = np.array(lst)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
%timeit arr**2

493 ns ± 4.12 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [28]:
arr = np.arange(10, 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr[0]

10

In [30]:
arr[-1]

24

In [31]:
arr[3:8]

array([13, 14, 15, 16, 17])

In [32]:
np.array([10,20,30,40.0])

array([10., 20., 30., 40.])

In [33]:
arr[1] = 110

In [34]:
print(arr)

[ 10 110  12  13  14  15  16  17  18  19  20  21  22  23  24]


In [35]:
arr

array([ 10, 110,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24])

In [36]:
lst2d = [ [4,5,6], [7,8,9] ]
lst2d

[[4, 5, 6], [7, 8, 9]]

In [37]:
arr2d = np.array(lst2d)
arr2d

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d*2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [39]:
arr2d + 2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
arr2d

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
len(arr2d)

2

In [42]:
arr2d.size

6

In [43]:
arr2d.shape

(2, 3)

In [44]:
arr2d.ndim

2

In [45]:
arr2d[1][1]

8

In [46]:
arr2d[1, 1]

8

In [47]:
arr

array([ 10, 110,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24])

In [48]:
arr.ndim

1

In [49]:
arr.shape

(15,)

In [50]:
np.array([1,2])

array([1, 2])

In [51]:
temp = np.array([[1,2]])
temp

array([[1, 2]])

In [52]:
temp.shape

(1, 2)

Q- What will be output for the following code?
```
a = np.array([1, 2, 3,4,5], ndmin = 2)
print(a)
```


A : [[1, 2, 3, 4, 5]]

B : [1, 2, 3, 4, 5]

C : Error

D : Null


In [53]:
np.array([1, 2, 3,4,5], ndmin=2)

array([[1, 2, 3, 4, 5]])

### Reshape

In [54]:
m1 = np.arange(10, 30, 1)
m1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [55]:
m1.shape

(20,)

In [56]:
m1.ndim

1

In [57]:
m1= m1.reshape((5,4))
m1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [58]:
m1.shape

(5, 4)

In [59]:
m1.reshape((4,5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [60]:
m1.reshape((2, 10))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [61]:
m1.reshape((4,4))

ValueError: cannot reshape array of size 20 into shape (4,4)

In [62]:
m1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [63]:
m1.reshape(2,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
np.arange(16).reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [65]:
# arr = np.linspace([12,12,13,14.0],18,3)
# arr

In [66]:
# np.linspace([1,2],[10,20],10,axis=1)

In [67]:
a = np.array([[1,2,3],[0,1,4]])
print(a.ndim)
print(a.shape)

2
(2, 3)


### Special Matrix

In [68]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.ones((3,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [72]:
np.identity(4, )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Slicing 

In [74]:
arr = np.arange(10, 30).reshape(4,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [75]:
arr[-1,-1]

29

In [76]:
arr[  1: , 2:4 ]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [77]:
arr[  : , :  ]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [78]:
arr[1:3 , :]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

`np.split()`

`np.hsplit()`

`np.vsplit()`


In [79]:
# np.split()

In [80]:
x = np.arange(10,100,10)
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
np.split(x, 3)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

In [82]:
np.split(x, [4,5,6])

[array([10, 20, 30, 40]), array([50]), array([60]), array([70, 80, 90])]

In [83]:
np.hsplit()

TypeError: hsplit() missing 2 required positional arguments: 'ary' and 'indices_or_sections'

In [84]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [85]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [86]:
np.mean(arr)

19.5

In [87]:
np.sum(arr)/20

19.5

## Operations

In [88]:
arr + 2

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31]])

In [89]:
arr*2

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])


What will be printed?
```
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a
print (c[2])
```

A : 7

B : 12

C : 10

D : 21

In [90]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c = c*a
c

array([ 1, 10, 21, 35, 72])

In [91]:
arr1 = np.arange(9).reshape(3,3)
arr2= np.arange(10, 19).reshape(3,3)

In [92]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [94]:
arr1 + arr2

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

## Masking

In [95]:
m1 = np.arange(10,22).reshape(3,4)
m1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [96]:
mask = m1 < 16
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [97]:
np.sum(mask)

6

In [98]:
m1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [99]:
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [100]:
m1[mask]

array([10, 11, 12, 13, 14, 15])

In [101]:
m1

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [102]:
m1[m1%2==0]

array([10, 12, 14, 16, 18, 20])

# Vectorisation

In [103]:
import math

In [104]:
math.log(134)

4.897839799950911

In [105]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [107]:
math.log(x)

TypeError: only length-1 arrays can be converted to Python scalars

In [108]:
vec_log = np.vectorize(math.log)

In [109]:
vec_log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [110]:
def custom_loss(a,b):
    return (a**2 + b**2)**0.5

In [111]:
vec_custom_loss = np.vectorize(custom_loss)

In [112]:
x = np.arange(10)
y = np.arange(10, 20)

In [113]:
vec_custom_loss(x, y)

array([10.        , 11.04536102, 12.16552506, 13.34166406, 14.56021978,
       15.8113883 , 17.08800749, 18.38477631, 19.6977156 , 21.02379604])

## Matrix Multiplication

In [114]:
A = np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
B = np.arange(12).reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
A*B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [117]:
np.matmul(A, B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [118]:
B = B.reshape(4,3)

In [119]:
np.matmul(A, B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [120]:
A@B

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [121]:
np.dot(A,B)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [122]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
np.transpose(A)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [124]:
A.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [125]:
A.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [126]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [127]:
np.ravel(A)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Merging of arrays
`np.hstack()`

`np.vstack()`

In [128]:
# from numpy import array

In [129]:
np.hstack()

TypeError: hstack() missing 1 required positional argument: 'tup'